### ISSUE TITLE
Scroll bug in popup

### ISSUE THREAD

**Issue by sanlju** [SOEP-Group/SOEP-Visualizer#136]
When the description is long in the popup and you scroll, the close button and the border is also following. Fix so that the close button is fixed at the top and the border is adjusted correctly.

<img width="399" alt="390902497-426c763e-38de-41a0-b83d-4f0845325bd9" src="https://github.com/user-attachments/assets/4c009e35-aa44-4d3e-9fe9-1536e9365f44">

**Comment by mohammed-shakir** [comment]
Thursday
