### ISSUE TITLE
Resizer bug

### ISSUE THREAD

**Issue by sanlju** [SOEP-Group/SOEP-Visualizer#161]
The resizer is not working correctly (in the burger menu).

**Comment by sanlju** [comment]
Because of these lines in header.js
<img width="510" alt="Skärmavbild 2024-12-12 kl  00 53 40" src="https://github.com/user-attachments/assets/1439a814-6531-48b2-830a-8817fba673c9" />

**Comment by RyuTribal** [comment]
Yeah fixed it in #180
