### ISSUE TITLE
Rate Limiter for API calls

### ISSUE THREAD

**Issue by syko240** [SOEP-Group/SOEP-Visualizer#23]
Implement/use some middleware to prevent postgreSQL from being overwhelmed.

Do a direct implementation using express, or something else.

[ref](https://blog.fluxninja.com/blog/protecting-postgresql-with-adaptive-rate-limiting#:~:text=To%20prevent%20PostgreSQL%20from%20being,the%20context%20of%20workload%20priorities.)

**Comment by RyuTribal** [comment]
Just get better server bro
