### ISSUE TITLE
DB race conditions

### ISSUE THREAD

**Issue by syko240** [SOEP-Group/SOEP-Visualizer#36]
Investigate whether there will be race conditions in the database when both c++ backend and visualizer want access to same data. Also propose a fix.

**Comment by syko240** [comment]
Probably wont be a problem. Should we read from committed data only? or lock sections of the db that is processing a transaction (not ideal)?

**Comment by RyuTribal** [comment]
is this not implemented in postgres already?

**Comment by syko240** [comment]
> is this not implemented in postgres already?

the first one is default
