### ISSUE TITLE
Gateway for load balancing.

### ISSUE THREAD

**Issue by syko240** [SOEP-Group/SOEP-Visualizer#39]
more info coming soon

**Comment by RyuTribal** [comment]
No idea what the point of this is

**Comment by syko240** [comment]
> No idea what the point of this is

I think the reason for this one is if we were to have multiple instances of soep, so instead of all users being on the same instance, you would distribute them to "even it out". But, if we dont have any performance issue with the current setup, and we dont expect more users using the service at the same time so that we might see performance issues, latency, etc., then this is unnecessary.
