### ISSUE TITLE
Add Events

### ISSUE THREAD

**Issue by sanlju** [SOEP-Group/SOEP-Visualizer#45]
* Design the events tab
  * Select location  
  * Select date and time 
  * Search bar to find event? 
  * Tabs for sun, moon and planet events [Done]
* Fetch events from repo (https://github.com/cosinekitty/astronomy/tree/master/source/js) [Done]
  * cache the events [Done]
* Decide what to be displayed on our website

**Comment by mohammed-shakir** [comment]
Söndag
