### ISSUE TITLE
Display the satellites on the website

### ISSUE THREAD

**Issue by sanlju** [SOEP-Group/SOEP-Visualizer#5]

**Comment by Limeiz** [comment]
Use instanced rendering for this, descibed here: https://github.com/SOEP-Group/SOEP-Visualizer/pull/14#issuecomment-2366728839

**Comment by Limeiz** [comment]
have to calculate relative position to our earth, make sure dimensions are correct, or re-map our coordinate system so satellites positions can be directly used as they are saved in database
