### ISSUE TITLE
Add function to pick satellite by clicking

### ISSUE THREAD

**Issue by Limeiz** [SOEP-Group/SOEP-Visualizer#94]
For all predictions, the user should be able to press the satellite field and then pick a satellite by clicking it, this should fill in that satellites name in the field.

**Comment by mohammed-shakir** [comment]
Wednesday

**Comment by RyuTribal** [comment]
It's taken too long now. We have a working version of this now in the branch: #193

**Comment by ArianAsghari** [comment]
Den är klar
