### ISSUE TITLE
UI Rework

### ISSUE THREAD

**Issue by Limeiz** [SOEP-Group/SOEP-Visualizer#95]
- [x] Move burger menu to the left
- [x] Make burger smaller
- [x] Add Events to header and burger menu
- [x] Fix icons for Events and Predictions
- [x] Add logo
- [x] Zoom in closer to earth
- [x] Zoom out further form earth
- [x] Change gizmo colors
- [x] Satellite Pop-up: 
          Move to upper right corner
          Make extendable downwards
          Make the content fit on laptop
          Make the link clickable (have a confirmation popup)
- [x] Add hover names for burger menu icons 
- [x] Design Predications tab
- [x] Design How-to tab
- [x] Design Settings tab
        Fix scroll bug and mobile look/Make text smaller
- [x] Make burger menu resizable
- [x] Make sure mobile version looks good/Make text smaller
- [x] Change colors and style to match the theme we want
        New colors on btn-blue css class (in inpus.css) Check!
- [x] Fix satellites search bar for mobile (search icon in header that expands)
- [x] Change gizmo
- [x] Move satellite search to middle or right side
- [x] Make section names in prediction tab clickable
- [x] Smaller sized satellites?
- [x] Change to non-bold text in satellite popup
- [x] Fix overlap issue for mobile popup
- [x] Change satellite color and/or design
- [x] Write about the satellite information in how-to tab (eventually rename the tab)

**Comment by mohammed-shakir** [comment]
Thursday
